import { BuildingType } from './building.constants';
import { Race } from './race.constants';

export type TroopTier = 'Basic' | 'Advanced' | 'Elite';
export type TroopType =
  | 'Infantry'
  | 'Ranged'
  | 'Cavalry'
  | 'Mage'
  | 'Siege'
  | 'Support';

export interface TroopDefinition {
  id: string;
  name: string;
  race: Race;
  tier: TroopTier;
  type: TroopType;
  cost: {
    food: number;
    wood: number;
    stone: number;
    gold: number;
  };
  buildTime: number; // in seconds
  attack: number;
  defense: number;
  speed: number; // tiles/hour
  capacity: number;
  requiredLevel: number;
  buildingType: BuildingType;
  abilities?: string[];
  description: string;
  metadata: Record<string, number | string | boolean>;
}

export const TROOP_TYPES: Record<string, TroopDefinition> = {
  // ==========================
  // HUMAN TROOPS
  // ==========================
  human_swordsman: {
    id: 'human_swordsman',
    name: 'Swordsman',
    race: Race.HUMAN,
    tier: 'Basic',
    type: 'Infantry',
    cost: { food: 50, wood: 20, stone: 10, gold: 0 },
    buildTime: 30,
    attack: 30,
    defense: 20,
    speed: 10,
    requiredLevel: 1,
    capacity: 10,
    buildingType: BuildingType.BARRACKS,
    description: 'A balanced front-line infantry unit trained to hold the line.',
    metadata: {},
  },
  human_archer: {
    id: 'human_archer',
    name: 'Archer',
    race: Race.HUMAN,
    tier: 'Basic',
    type: 'Ranged',
    cost: { food: 40, wood: 40, stone: 0, gold: 0 },
    buildTime: 35,
    attack: 25,
    defense: 10,
    speed: 12,
    requiredLevel: 3,
    capacity: 8,
    buildingType: BuildingType.BARRACKS,
    description: 'Long-ranged attacker that deals damage before the enemy reaches melee.',
    metadata: {},
  },
  human_knight: {
    id: 'human_knight',
    name: 'Knight',
    race: Race.HUMAN,
    tier: 'Advanced',
    type: 'Cavalry',
    requiredLevel: 1,
    buildingType: BuildingType.STABLE,
    cost: { food: 90, wood: 40, stone: 20, gold: 60 },
    buildTime: 70,
    attack: 50,
    defense: 40,
    speed: 16,
    capacity: 15,
    description: 'Heavily-armored cavalry with devastating charges.',
    metadata: {},
  },
  human_cleric: {
    id: 'human_cleric',
    name: 'Cleric',
    race: Race.HUMAN,
    tier: 'Advanced',
    requiredLevel: 1,
    type: 'Support',
    buildingType: BuildingType.SHRINE,
    cost: { food: 30, wood: 20, stone: 10, gold: 50 },
    buildTime: 45,
    attack: 10,
    defense: 20,
    speed: 9,
    capacity: 5,
    abilities: ['Heal', 'Blessing'],
    description: 'Support unit that heals allies and boosts morale.',
    metadata: {},
  },
  human_catapult: {
    id: 'human_catapult',
    name: 'Catapult',
    race: Race.HUMAN,
    tier: 'Elite',
    buildingType: BuildingType.WORKSHOP,
    type: 'Siege',
    requiredLevel: 1,
    cost: { food: 60, wood: 100, stone: 80, gold: 40 },
    buildTime: 110,
    attack: 80,
    defense: 20,
    speed: 4,
    capacity: 0,
    abilities: ['SiegeAttack'],
    description: 'Destroys enemy fortifications from a distance.',
    metadata: {},
  },
  human_paladin: {
    id: 'human_paladin',
    name: 'Paladin',
    race: Race.HUMAN,
    tier: 'Elite',
    requiredLevel: 5,
    type: 'Cavalry',
    buildingType: BuildingType.STABLE,
    cost: { food: 100, wood: 50, stone: 20, gold: 80 },
    buildTime: 90,
    attack: 60,
    defense: 50,
    speed: 18,
    capacity: 20,
    abilities: ['HealNearby', 'Inspire'],
    description: 'An elite knight with healing magic and a fearless charge.',
    metadata: {},
  },

  // ==========================
  // ORC TROOPS
  // ==========================
  orc_grunt: {
    id: 'orc_grunt',
    name: 'Grunt',
    race: Race.ORC,
    requiredLevel: 1,
    tier: 'Basic',
    type: 'Infantry',
    cost: { food: 60, wood: 10, stone: 20, gold: 0 },
    buildTime: 30,
    attack: 40,
    buildingType: BuildingType.BARRACKS,
    defense: 15,
    speed: 9,
    capacity: 12,
    description: 'Aggressive front-line brawler with high raw strength.',
    metadata: {},
  },
  orc_raider: {
    id: 'orc_raider',
    name: 'Raider',
    race: Race.ORC,
    requiredLevel: 1,
    tier: 'Basic',
    type: 'Cavalry',
    cost: { food: 70, wood: 20, stone: 10, gold: 10 },
    buildTime: 40,
    attack: 35,
    buildingType: BuildingType.STABLE,
    defense: 10,
    speed: 15,
    capacity: 20,
    description: 'Fast cavalry unit ideal for raids and hit-and-run tactics.',
    metadata: {},
  },
  orc_berserker: {
    id: 'orc_berserker',
    name: 'Berserker',
    race: Race.ORC,
    requiredLevel: 3,
    tier: 'Advanced',
    type: 'Infantry',
    buildingType: BuildingType.BARRACKS,
    cost: { food: 90, wood: 30, stone: 20, gold: 30 },
    buildTime: 60,
    attack: 60,
    defense: 25,
    speed: 11,
    capacity: 15,
    abilities: ['Rage'],
    description: 'Fights harder when injured. Terrifying in melee.',
    metadata: {},
  },
  orc_shaman: {
    id: 'orc_shaman',
    name: 'Shaman',
    race: Race.ORC,
    requiredLevel: 1,
    buildingType: BuildingType.SHRINE,
    tier: 'Advanced',
    type: 'Mage',
    cost: { food: 40, wood: 40, stone: 10, gold: 50 },
    buildTime: 50,
    attack: 25,
    defense: 15,
    speed: 10,
    capacity: 5,
    abilities: ['Bloodlust', 'TotemAura'],
    description: 'A spiritual caster that enhances nearby allies.',
    metadata: {},
  },
  orc_warboar_rider: {
    id: 'orc_warboar_rider',
    name: 'Warboar Rider',
    race: Race.ORC,
    tier: 'Elite',
    type: 'Cavalry',
    requiredLevel: 5,
    cost: { food: 100, wood: 20, stone: 30, gold: 40 },
    buildTime: 85,
    attack: 70,
    defense: 40,
    buildingType: BuildingType.STABLE,
    speed: 20,
    capacity: 18,
    description: 'Fast, reckless cavalry unit — ideal for hit-and-run attacks.',
    metadata: {},
  },

  // ==========================
  // ELF TROOPS
  // ==========================
  elf_scout: {
    id: 'elf_scout',
    name: 'Scout',
    race: Race.ELF,
    tier: 'Basic',
    type: 'Ranged',
    requiredLevel: 1,
    buildingType: BuildingType.BARRACKS,
    cost: { food: 30, wood: 50, stone: 0, gold: 0 },
    buildTime: 25,
    attack: 20,
    defense: 10,
    speed: 16,
    capacity: 6,
    abilities: ['RevealMap'],
    description: 'Light-footed archer who excels at gathering intel.',
    metadata: {},
  },
  elf_blademaster: {
    id: 'elf_blademaster',
    name: 'Blademaster',
    race: Race.ELF,
    tier: 'Advanced',
    requiredLevel: 5,
    type: 'Infantry',
    buildingType: BuildingType.BARRACKS,
    cost: { food: 70, wood: 40, stone: 10, gold: 50 },
    buildTime: 55,
    attack: 50,
    defense: 30,
    speed: 14,
    capacity: 10,
    abilities: ['Dodge'],
    description: 'Elegant and deadly swordsman with blinding speed.',
    metadata: {},
  },
  elf_druid: {
    id: 'elf_druid',
    name: 'Druid',
    race: Race.ELF,
    requiredLevel: 1,
    tier: 'Elite',
    buildingType: BuildingType.SHRINE,
    type: 'Mage',
    cost: { food: 50, wood: 80, stone: 20, gold: 100 },
    buildTime: 95,
    attack: 20,
    defense: 20,
    speed: 10,
    capacity: 5,
    abilities: ['Heal', 'Entangle'],
    description:
      'Magical support unit that controls nature to heal allies or trap enemies.',
    metadata: {},
  },

  // ==========================
  // DWARF TROOPS
  // ==========================
  dwarf_guardian: {
    id: 'dwarf_guardian',
    name: 'Guardian',
    race: Race.DWARF,
    requiredLevel: 1,
    tier: 'Basic',
    buildingType: BuildingType.BARRACKS,
    type: 'Infantry',
    cost: { food: 40, wood: 10, stone: 40, gold: 10 },
    buildTime: 35,
    attack: 20,
    defense: 40,
    speed: 7,
    capacity: 6,
    description: 'Slow but durable protector with high fortitude.',
    metadata: {},
  },
  dwarf_crossbowman: {
    id: 'dwarf_crossbowman',
    name: 'Crossbowman',
    race: Race.DWARF,
    tier: 'Basic',
    requiredLevel: 3,
    buildingType: BuildingType.BARRACKS,
    type: 'Ranged',
    cost: { food: 35, wood: 45, stone: 10, gold: 5 },
    buildTime: 40,
    attack: 28,
    defense: 20,
    speed: 8,
    capacity: 6,
    description: 'Heavy ranged attacker with armor-piercing bolts.',
    metadata: {},
  },
  dwarf_hammerer: {
    id: 'dwarf_hammerer',
    name: 'Hammerer',
    race: Race.DWARF,
    tier: 'Advanced',
    requiredLevel: 5,
    buildingType: BuildingType.BARRACKS,
    type: 'Infantry',
    cost: { food: 60, wood: 30, stone: 50, gold: 30 },
    buildTime: 60,
    attack: 55,
    defense: 45,
    speed: 7,
    capacity: 10,
    description: 'Wields massive warhammers to crush enemy armor.',
    metadata: {},
  },
  dwarf_runesmith: {
    id: 'dwarf_runesmith',
    name: 'Runesmith',
    race: Race.DWARF,
    tier: 'Advanced',
    type: 'Mage',
    requiredLevel: 1,
    buildingType: BuildingType.SHRINE,
    cost: { food: 30, wood: 20, stone: 40, gold: 60 },
    buildTime: 65,
    attack: 20,
    defense: 25,
    speed: 6,
    capacity: 5,
    abilities: ['RuneShield', 'Stun'],
    description: 'Magical smith who casts protective runes and disables foes.',
    metadata: {},
  },
  dwarf_engineer: {
    id: 'dwarf_engineer',
    name: 'Engineer',
    race: Race.DWARF,
    requiredLevel: 1,
    buildingType: BuildingType.WORKSHOP,
    tier: 'Advanced',
    type: 'Siege',
    cost: { food: 50, wood: 80, stone: 60, gold: 30 },
    buildTime: 75,
    attack: 45,
    defense: 30,
    speed: 8,
    capacity: 14,
    abilities: ['DeployTurret'],
    description: 'Crafts explosive tools and deployable defenses during combat.',
    metadata: {},
  },
  dwarf_battlemaster: {
    id: 'dwarf_battlemaster',
    name: 'Battlemaster',
    race: Race.DWARF,
    tier: 'Elite',
    requiredLevel: 5,
    buildingType: BuildingType.BARRACKS,
    type: 'Infantry',
    cost: { food: 100, wood: 20, stone: 50, gold: 100 },
    buildTime: 100,
    attack: 55,
    defense: 60,
    speed: 9,
    capacity: 10,
    abilities: ['BattleCry'],
    description: 'Leads the charge with a roar that boosts ally strength.',
    metadata: {},
  },

  // ==========================
  // UNDEAD TROOPS
  // ==========================
  undead_zombie: {
    id: 'undead_zombie',
    name: 'Zombie',
    race: Race.UNDEAD,
    tier: 'Basic',
    requiredLevel: 1,
    buildingType: BuildingType.BARRACKS,
    type: 'Infantry',
    cost: { food: 20, wood: 0, stone: 0, gold: 0 },
    buildTime: 20,
    attack: 15,
    defense: 10,
    speed: 6,
    capacity: 4,
    abilities: ['Infect'],
    description: 'Mindless undead soldier, cheap and numerous.',
    metadata: {},
  },
  undead_skeleton_archer: {
    id: 'undead_skeleton_archer',
    name: 'Skeleton Archer',
    race: Race.UNDEAD,
    requiredLevel: 2,
    tier: 'Basic',
    buildingType: BuildingType.BARRACKS,
    type: 'Ranged',
    cost: { food: 25, wood: 30, stone: 0, gold: 5 },
    buildTime: 30,
    attack: 20,
    defense: 8,
    speed: 8,
    capacity: 6,
    description: 'Unliving bowmen that rain down arrows in eerie silence.',
    metadata: {},
  },
  undead_ghoul: {
    id: 'undead_ghoul',
    name: 'Ghoul',
    race: Race.UNDEAD,
    requiredLevel: 4,
    tier: 'Advanced',
    buildingType: BuildingType.BARRACKS,
    type: 'Infantry',
    cost: { food: 60, wood: 0, stone: 20, gold: 20 },
    buildTime: 50,
    attack: 45,
    defense: 25,
    speed: 10,
    capacity: 8,
    abilities: ['PoisonClaws'],
    description: 'Fast and feral predator with venomous claws.',
    metadata: {},
  },
  undead_banshee: {
    id: 'undead_banshee',
    name: 'Banshee',
    race: Race.UNDEAD,
    tier: 'Advanced',
    requiredLevel: 1,
    type: 'Mage',
    cost: { food: 40, wood: 0, stone: 30, gold: 60 },
    buildTime: 70,
    buildingType: BuildingType.SHRINE,
    attack: 25,
    defense: 15,
    speed: 11,
    capacity: 4,
    abilities: ['Wail', 'FearAura'],
    description: 'Wails to instill fear and disrupt enemy morale.',
    metadata: {},
  },
  undead_abomination: {
    id: 'undead_abomination',
    name: 'Abomination',
    race: Race.UNDEAD,
    tier: 'Elite',
    requiredLevel: 7,
    buildingType: BuildingType.BARRACKS,
    type: 'Infantry',
    cost: { food: 120, wood: 0, stone: 40, gold: 80 },
    buildTime: 100,
    attack: 70,
    defense: 50,
    speed: 7,
    capacity: 12,
    description: 'A grotesque fusion of corpses, unstoppable in melee.',
    metadata: {},
  },
  undead_necromancer: {
    id: 'undead_necromancer',
    name: 'Necromancer',
    race: Race.UNDEAD,
    tier: 'Elite',
    requiredLevel: 1,
    type: 'Mage',
    cost: { food: 30, wood: 50, stone: 20, gold: 120 },
    buildTime: 100,
    attack: 25,
    defense: 25,
    buildingType: BuildingType.SHRINE,
    speed: 9,
    capacity: 5,
    abilities: ['RaiseDead', 'Curse'],
    description:
      'Summons the fallen and weakens the living. Core to Undead dominance.',
    metadata: {},
  },
};
